version: '3.4'

services:
    rsync:
        image: xigen/archmirror
        restart: always
        tty: true
        environment:
            # The source URL of the mirror you want to sync from.
            # If you are a tier 1 mirror use rsync.archlinux.org, for example like this:
            # rsync://rsync.archlinux.org/ftp_tier1
            # Otherwise chose a tier 1 mirror from this list and use its rsync URL:
            # https://www.archlinux.org/mirrors/
            source_url: rsync://ftp.nluug.nl/archlinux/

            # An HTTP(S) URL pointing to the 'lastupdate' file on your chosen mirror.
            # If you are a tier 1 mirror use: http://rsync.archlinux.org/lastupdate
            # Otherwise use the HTTP(S) URL from your chosen mirror.
            lastupdate_url: http://ftp.nluug.nl/os/Linux/distr/archlinux/lastupdate
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
          - ./data:/data

    httpd:
        image: httpd:alpine
        volumes:
          - ./data:/usr/local/apache2/htdocs
        ports:
            - "80:80"
